{% set version = "1.5.1" %}

package:
  name: mcpl
  version: {{ version }}

source:
  url: https://github.com/mctools/mcpl/archive/v{{ version }}.tar.gz
  sha256: ded8da682fda348b8ceb435db0eb0923c03f2410e069932ee2fb146ea34bf47a
  #NB get sha256 with: curl -sL <URL> | openssl sha256
  fn: mcpl-src.tar.gz
  folder: src

build:
  number: 2
  skip: true  # [win]
  skip: true  # [py<36]

requirements:
  build:
    - cmake
    - make  # [not win]
    - zlib
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - zlib
  run:
    - python
    - numpy
    - zlib

test:
  requires:
    - cmake
  imports:
    - mcpl
  commands:
    - mcpl-config --help
    - mcpl-config -s
    - mcpltool --version
    - mcpltool --help
    - ssw2mcpl --help
    - mcpl2ssw --help
    - phits2mcpl --help
    - mcpl2phits --help
    - pymcpltool --help
    - cmake --find-package -DNAME=MCPL -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST

about:
  home: https://github.com/mctools/mcpl
  summary: MCPL - Monte Carlo Particle Lists
  description: |
    Utilities and API for accessing MCPL (.mcpl) files. MCPL is a binary
    format with lists of particle state information, for interchanging and
    reshooting events between various Monte Carlo simulation applications.
  license: CC0-1.0
  license_family: CC
  license_file: src/LICENSE
  doc_url: https://mctools.github.io/mcpl
  dev_url: https://github.com/mctools/mcpl

extra:
  recipe-maintainers:
    - tkittel
