{% set version = "2.0.0" %}

package:
  name: mcpl
  version: {{ version }}

source:
  url: https://github.com/mctools/mcpl/archive/v{{ version }}.tar.gz
  sha256: c451d86abf17181edb8c36cf77b6dcbbe22f1d3c30df84321f8c17eda7c5a873
  #NB get sha256 with: curl -sL <URL> | openssl sha256
  folder: src

build:
  noarch: python
  number: 0

outputs:
  - name: mcpl-lib
    script: build_core.sh  # [unix]
    script: build_core.bat  # [win]
    requirements:
      build:
        - cmake >=3.25
        - make  # [not win]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - zlib
      host:
        - zlib
      run:
        - zlib
    test:
      requires:
        - cmake >=3.25
        - make  # [not win]
        - c-compiler
      source_files:
        - ./src/examples/downstream_cmake
        - ./src/examples/example.mcpl
      script: test_core.sh  # [unix]
      script: test_core.bat  # [win]

  - name: mcpl-core
    build:
      noarch: python
      script: python -m pip install "./src/mcpl_core/empty_pypkg" -vv --no-deps --no-build-isolation
    requirements:
      build:
        - python  {{ python_min }}  # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
      host:
        - python  {{ python_min }}
        - pip
        - setuptools >=75.3.2
      run:
        - python >={{ python_min }}
        - mcpl-lib ={{ version }}
    test:
      requires:
        - python {{ python_min }}
        - pip
      commands:
        - pip check
        - pip show mcpl-core
        - conda list

  - name: mcpl-python
    build:
      noarch: python
      script: python -m pip install "./src/mcpl_python" -vv --no-deps --no-build-isolation
      entry_points:
        - pymcpltool = mcpl.mcpl:main
    requirements:
      build:
        - python  {{ python_min }}  # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
      host:
        - python  {{ python_min }}
        - pip
        - setuptools >=64.0
      run:
        - python >={{ python_min }}
        - numpy >=1.22
    test:
      imports:
        - mcpl
      requires:
        - python {{ python_min }}
        - pip
      commands:
        - pip check
        - pip show mcpl-python
        - pymcpltool --help

  - name: mcpl
    build:
      noarch: python
      script: python -m pip install "./src/mcpl_metapkg" -vv --no-deps --no-build-isolation
    requirements:
      build:
        - python  {{ python_min }}  # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
      host:
        - python  {{ python_min }}
        - pip
        - setuptools >=75.3.2
      run:
        - python >={{ python_min }}
        - mcpl-core ={{ version }}
        - mcpl-python ={{ version }}
    test:
      requires:
        - python {{ python_min }}
        - pip
        - cmake >=3.25
        - make  # [not win]
        - c-compiler
      imports:
        - mcpl
      commands:
        - mcpl-config --help
        - mcpl-config -s
        - mcpltool --version
        - mcpltool --help
        - pymcpltool --help
        - cmake --find-package -DNAME=MCPL -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST

  - name: mcpl-extra
    script: build_extra.sh  # [unix]
    script: build_extra.bat  # [win]
    requirements:
      build:
        - cmake >=3.25
        - make  # [not win]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
      host:
        - mcpl-lib ={{ version }}
      run:
        - mcpl-lib ={{ version }}
    test:
      commands:
        - ssw2mcpl --help
        - mcpl2ssw --help
        - phits2mcpl --help
        - mcpl2phits --help

about:
  home: https://github.com/mctools/mcpl
  summary: MCPL - Monte Carlo Particle Lists
  description: |
    Utilities and API for accessing MCPL (.mcpl) files. MCPL is a binary
    format with lists of particle state information, for interchanging and
    reshooting events between various Monte Carlo simulation applications.
  license: Apache-2.0
  license_family: Apache
  license_file: src/LICENSE
  doc_url: https://mctools.github.io/mcpl
  dev_url: https://github.com/mctools/mcpl

extra:
  recipe-maintainers:
    - tkittel
